create table USER (
USER_ID VARCHAR(40) PRIMARY KEY,
ROLE VARCHAR(16) NOT NULL,
PASSWORD VARCHAR(160) NOT NULL,
CREATETS DATETIME NOT NULL,
CREATE_USER_ID VARCHAR(40),
MODIFYTS DATETIME NOT NULL,
MODIFY_USER_ID VARCHAR(40));

create table JOG_INFO (
JOG_ID VARCHAR(40) PRIMARY KEY,
USER_ID VARCHAR(40) NOT NULL,
JOG_DATE DATETIME NOT NULL,
JOG_DISTANCE DECIMAL(8, 2) NOT NULL,
JOG_TIME DECIMAL(8, 2) NOT NULL,
JOG_LOCATION_LAT DECIMAL(8, 2) NOT NULL,
JOG_LOCATION_LONG DECIMAL(8, 2) NOT NULL,
TEMPERATURE DECIMAL(8, 2) NOT NULL,
PRESSURE DECIMAL(8, 2) NOT NULL,
HUMIDITY DECIMAL(8, 2) NOT NULL,
WIND_SPEED DECIMAL(8, 2) NOT NULL,
CREATETS DATETIME NOT NULL,
CREATE_USER_ID VARCHAR(40),
MODIFYTS DATETIME NOT NULL,
MODIFY_USER_ID VARCHAR(40),
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);	


create table AUTH_TOKEN_INFO (
USER_ID VARCHAR(40) NOT NULL,
AUTH_TOKEN VARCHAR(40) NOT NULL,
EXPIRY_DATE DATETIME NOT NULL,
CREATETS DATETIME NOT NULL,
CREATE_USER_ID VARCHAR(40),
MODIFYTS DATETIME NOT NULL,
MODIFY_USER_ID VARCHAR(40)
);


